# render.yaml
services:
  - type: web
    name: closureme-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: STORAGE_MODE
        value: disabled
      - key: DATABASE_URL
        fromDatabase:
          name: closureme-db
          property: connectionString

databases:
  - name: closureme-db
    plan: free
