-- 建立序列
CREATE SEQUENCE IF NOT EXISTS public.char_appearance_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS public.char_images_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS public.char_memory_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS public.users_id_seq START WITH 1 INCREMENT BY 1;

-- 建立表
CREATE TABLE IF NOT EXISTS public.users (
    id integer PRIMARY KEY DEFAULT nextval('public.users_id_seq'::regclass),
    username varchar(255) NOT NULL UNIQUE,
    password text NOT NULL,
    email text UNIQUE
);

CREATE TABLE IF NOT EXISTS public.char_images (
    id integer PRIMARY KEY DEFAULT nextval('public.char_images_id_seq'::regclass),
    user_id integer REFERENCES public.users(id) ON DELETE CASCADE,
    file_name varchar(255) NOT NULL,
    file_path varchar(500) NOT NULL,
    uploaded_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.char_profile (
    id integer PRIMARY KEY DEFAULT nextval('public.char_appearance_id_seq'::regclass),
    image_id integer REFERENCES public.char_images(id) ON DELETE CASCADE,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    file_path varchar(500)
);

CREATE TABLE IF NOT EXISTS public.char_memory (
    id integer PRIMARY KEY DEFAULT nextval('public.char_memory_id_seq'::regclass),
    image_id integer REFERENCES public.char_images(id) ON DELETE CASCADE,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    file_path varchar(500)
);

CREATE TABLE IF NOT EXISTS public.char_voice (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id integer REFERENCES public.char_images(id) ON DELETE CASCADE,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    file_path text
);